version: "3.9"
services:

  discovery-server:
    image: spring-overview/discovery-server
    build:
      context: discovery-server
    env_file:
      - .env
    ports:
      - ${DISCOVERY_SERVER_EXTERNAL_PORT:-18761}:8761

  api-gateway:
    image: spring-overview/api-gateway
    build:
      context: api-gateway
    env_file:
      - .env
    ports:
      - ${API_GATEWAY_EXTERNAL_PORT:-18765}:8765
    depends_on:
      discovery-server:
        condition: service_healthy

  dummy-service:
    image: spring-overview/dummy-service
    build:
      context: dummy
    env_file:
      - .env
    environment:
      - SERVICE_PROFILES
    depends_on:
      discovery-server:
        condition: service_healthy
