server:
  port: 8765

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping: true

spring:
  application:
    name: api-gateway

  # CORS
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

      # ROUTES!!!
      routes:
        - id: dummy
          uri: lb://dummy
          predicates:
            - Path=/dummy/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka

# ACTUATORS
management.endpoints.jmx.exposure.exclude:
management.endpoints.jmx.exposure.include: info,health,env,loggers,metrics,prometheus
management.endpoints.web.exposure.exclude:
management.endpoints.web.exposure.include: info,health,env,loggers,metrics,prometheus
management.endpoint.info.enabled: true
management.endpoint.loggers.enabled: true

# Logging
logging.file.name: /var/log/${spring.application.name}.log
logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 1
      clean-history-on-start: true
